[project]
name = "niles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "discord-py>=2.7.1",
  "loguru>=0.7.3",
  "pydantic-settings>=2.14.1",
]

[project.scripts]
niles = "niles:main"

[build-system]
requires = ["uv_build>=0.11.13,<0.12.0"]
build-backend = "uv_build"

[tool.pyright]
pythonVersion = "3.14"
typeCheckingMode = "strict"
reportImportCycles = true
